accounts/urls.py
from django.urls import path
from .views import login_user, logout_user

app_name = 'accounts'

urlpatterns = [
    path(route='login', view=login_user, name="login"),
    path(route='logout', view=logout_user, name="logout"),
]

appcore/urls.py
from django.urls import path
from .views import ProductsView, search_post_request, IndexView, ProductView, add_to_shopping_cart, CartView, remove_from_shopping_cart, SearchView, ContactView, AboutView, FAQView, AccountView, ShippingDetailsView, checkout_complete, TaggedProducts, product_review, change_quantity, get_brand_products, stripe_config, create_checkout_session

app_name = "core"

urlpatterns = [
    path(route="", view=IndexView.as_view(), name="index"),
    path(route="products/", view=ProductsView.as_view(), name="products"),
    path(route="<int:pk>/product_details/", view=ProductView.as_view(), name="product_details"),
    path(route="<int:product_id>/post_review/", view=product_review, name="post_review"),
    path(route="search", view=search_post_request, name="search_post_request"),
    path(route="get_brand_products", view=get_brand_products, name="get_brand_products"),
    path(route="<int:product_id>/add_to_cart", view=add_to_shopping_cart, name="add-to-cart"),
    path(route="checkout_cart/", view=CartView.as_view(), name="checkout_cart"),
    path(route="<int:product_id>_<str:change>_quantity", view=change_quantity, name="change_quantity"),
    path(route="checkout_shipping/", view=ShippingDetailsView.as_view(), name="checkout_shipping"),
    path(route="checkout_payment/", view=checkout_complete, name="checkout_payment"),
    path(route="remove_from_shopping_cart/<int:item_id>", view=remove_from_shopping_cart, name="remove-from-cart"),
    path(route="search/query=<str:search_query>", view=SearchView.as_view(), name="search_with_query"),
    path(route="<str:query>_products/", view=TaggedProducts.as_view(), name="tagged_products"),
    path(route="contact-us/", view=ContactView.as_view(), name="contact_us"),
    path(route="about-us/", view=AboutView.as_view(), name="about_us"),
    path(route="faq/", view=FAQView.as_view(), name="faq"),
    path(route="my_account/", view=AccountView.as_view(), name="my_account"),
    path(route="stripe_config", view=stripe_config, name="stripe_config"),
    path(route="create_checkout_session", view=create_checkout_session, name="create_checkout_session"),
    # path(route="get_products_by_range", view=product_list, name="products_by_range"),
]

myecsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("appcore.urls")),
    path('accounts/', include("accounts.urls")),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appcore/models.py
from django.db import models
from django.contrib import admin
from django.contrib.postgres.fields import ArrayField
from django.utils import timezone
from django.conf import settings
from django.urls import reverse


class Product(models.Model):
    product_name = models.CharField(max_length=50)
    product_price = models.FloatField(verbose_name="Price")
    product_type = models.CharField(max_length=20)
    quantity_left = models.IntegerField(default=1)
    tags = ArrayField(
        base_field=models.CharField(max_length=20),
        default=list,
    )
    product_tagline = models.CharField(max_length=50, blank=True)
    info_lines = ArrayField(
        base_field=models.CharField(max_length=100),
        default=list
    )
    discount = models.IntegerField(default=0)
    manufacturer = models.CharField(max_length=30, default="")
    descriptions = models.JSONField(default=dict, blank=True)
    page_photos = ArrayField(
        base_field=models.CharField(max_length=200), default=list
    )
    additional_info = models.JSONField(default=dict, blank=True)
    price_id = models.CharField(max_length=200, default="")
    product_image = models.ImageField(upload_to='images/', verbose_name="Primary Image")

    
    def __str__(self) -> str:
        return self.product_name

    @admin.display(
            boolean=True,
            description="In Stock?"
    )
    def in_stock(self) -> bool:
        return self.quantity_left > 0
    
    def discounted_price(self):
        return round(float(int(self.product_price * (1 - (self.discount / 100)))), 2)
    
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            "product_id": f"{self.id}"
        })
    

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    @property
    def total_cost(self):
        return self.product.discounted_price() * self.quantity

    def __str__(self) -> str:
        return f"{self.quantity}x{self.product}"


class ShoppingCart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return f"{self.user.email}"
    
    @property
    def subtotal(self):
        total = 0
        for each in self.items.all():
            total += each.quantity * each.product.discounted_price()
        return total


class ShippingDetails(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20, blank=False)
    last_name = models.CharField(max_length=20, blank=False)
    company_name = models.CharField(max_length=40, blank=True)
    area_code = models.IntegerField(blank=False)
    primary_phone = models.CharField(max_length=30)
    address_1 = models.CharField(max_length=100, blank=False)
    address_2 = models.CharField(max_length=100, blank=True)
    zip_code = models.CharField(max_length=20, blank=False)

    def __str__(self) -> str:
        return self.user.email

class PaymentDetails(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    cardholder = models.CharField(max_length=30)
    card_number = models.CharField(max_length=16)
    payment_type = models.CharField(max_length=20, blank=True)
    mm = models.CharField(max_length=2)
    yy = models.CharField(max_length=4)
    number = models.CharField(max_length=3)

    def __str__(self) -> str:
        return self.user.email


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    review = models.CharField(max_length=500)
    rating = models.CharField(default="5", max_length=1)
    date = models.DateTimeField(default=timezone.now, blank=True)

    def __str__(self) -> str:
        return f"{self.product}-{self.user.email}"

appcore/forms.py
from django import forms
from .models import ShippingDetails, PaymentDetails, ProductReview


class ShippingDetailsForm(forms.ModelForm):
    class Meta:
        model = ShippingDetails
        exclude = ["csrfmiddlewaretoken", "user"]


class PaymentDetailsForm(forms.ModelForm):
    class Meta:
        model = PaymentDetails
        exclude = ["csrfmiddlewaretoken", "user"]


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        exclude = ["csrfmiddlewaretoken", "name"]


class PriceRangeForm(forms.Form):
    min_price = forms.DecimalField(label='Minimum Price', min_value=0)
    max_price = forms.DecimalField(label='Maximum Price', min_value=0)

appcore/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from .models import Product, OrderItem, ShoppingCart, ShippingDetails, ProductReview
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.urls import reverse
from .forms import ShippingDetailsForm, ProductReviewForm, PriceRangeForm
from django.contrib.postgres.search import SearchVector
from django.http import HttpResponse
from django.http.response import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
import stripe
from django.core.mail import send_mail
from .helpers import to_dict, get_html_email
from django.views import generic


class IndexView(generic.TemplateView):
    template_name = 'appcore/index.html'
    context_object_name = 'index_context'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        trending_products = Product.objects.extra(where=['%s ILIKE ANY (tags)'], params=['trending',])
        mobile_phones = Product.objects.extra(where=['%s ILIKE ANY (tags)'], params=['mobile',])
        mobile_phone_brands = mobile_phones.values_list("manufacturer")
        mobile_phone_brands = set(brand[0] for brand in mobile_phone_brands)
        tablets = Product.objects.extra(where=['%s ILIKE ANY (tags)'], params=['tablet',])
        tablet_brands = tablets.values_list("manufacturer")
        tablet_brands = set(brand[0] for brand in tablet_brands)
        context.update({"tablets": tablets})
        context.update({"mobile_phones": mobile_phones})
        context.update({'trending_products': trending_products, 'mobile_brands': mobile_phone_brands, 'tablet_brands': tablet_brands})
        return context


class ProductsView(generic.ListView):
    model = Product
    template_name = 'appcore/product.html'
    context_object_name = 'products'
    
    def get_queryset(self) -> QuerySet[Any]:
        price_from = self.request.GET.get('price_from', None)
        price_to = self.request.GET.get('price_to', None)

        if not price_from or not price_to:
            return Product.objects.all()

        return Product.objects.filter(product_price__lte=price_to, product_price__gte=price_from)


class TaggedProducts(generic.ListView):
    model = Product
    context_object_name = 'possible_results'
    template_name = 'appcore/tagged_products.html'

    def get_queryset(self) -> QuerySet[Any]:
        search_query = self.kwargs['query']
        possible_results = Product.objects.annotate(
            search=SearchVector("tags", "product_name", "manufacturer")
        ).filter(search=search_query)
        return possible_results


class ProductView(generic.DetailView):
    model = Product
    template_name = 'appcore/product_detail.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        product_id = self.kwargs['pk']
        context = {}
        product = Product.objects.get(pk=product_id)
        reviews = ProductReview.objects.filter(product=product_id)
        suggested = Product.objects.annotate(search=SearchVector("tags", "product_name", "manufacturer"),
                                                    ).filter(search=product.tags[0])
        suggested = suggested[:min(len(suggested), 6)]
        context.update({"product": product, 'suggested': suggested, 'reviews': reviews})
        return context
    

class SearchView(generic.ListView):
    model = Product
    template_name = 'appcore/search_results.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        search_query = self.kwargs['search_query']
        context = {}
        possible_results = Product.objects.annotate(search=SearchVector("tags", "product_name", "manufacturer"),
                                                    ).filter(search=search_query)
        context.update({'possible_results': possible_results, "query": search_query, "total_results": len(possible_results)})
        return context
    

class CartView(generic.View):

    def get(self, request, *args: Any, **kwargs: Any) -> HttpResponse:
        if request.GET.get("payment", False) == "cancelled":
            messages.info(request, "Your payment was cancelled. No Transaction was made.")
        self.template_name = 'appcore/checkout_cart.html'
        return render(request, self.template_name, {})


    def post(self, request, *args, **kwargs):
        return render(request, 'appcore/checkout_info.html', {})
    

class ShippingDetailsView(generic.View):

    def get(self, request, *args: Any, **kwargs: Any) -> HttpResponse:
        return render(request, 'appcore/checkout_info.html')
    
    def post(self, request, *args, **kwargs):
        exists = ShippingDetails.objects.filter(user=request.user).exists()
        form = ShippingDetailsForm(request.POST)
        if form.is_valid():
            if exists:
                return redirect('core:checkout_billing')
            f = form.save(commit=False)
            f.user_id = request.user.id
            f.save()
            return redirect('core:checkout_billing')
        messages.error(request, "Please fill all required fileds correctly.")
        return redirect('core:checkout_shipping')


class ContactView(generic.TemplateView):
    template_name = 'appcore/contact_us.html'


class FAQView(generic.TemplateView):
    template_name = 'appcore/faq.html'


class AccountView(generic.TemplateView):
    template_name = 'appcore/my_account.html'


class AboutView(generic.TemplateView):
    template_name = 'appcore/about_us.html'


def get_brand_products(request):
    brand = request.POST["brand"]
    products = request.POST["products"]
    if brand.lower() == "all brands":
        possible_results = Product.objects.extra(where=['%s ILIKE ANY (tags)'], params=[products,])
    else:
        possible_results = Product.objects.filter(manufacturer=brand).extra(where=['%s ILIKE ANY (tags)'], params=[products,])
    res = []
    for each in possible_results.all():
        res.append(to_dict(each))
    return HttpResponse(json.dumps({"products": res}), content_type = 'application/javascript; charset=utf8')
        

def product_review(request, product_id):
    form = ProductReviewForm(request.POST)
    if form.is_valid():
        form.save()
        messages.success(request, "Review Saved.")
        return redirect('core:product_details', product_id = product_id)
    messages.error(request ,"Please fill all fields correctly.")
    return redirect("core:product_details", product_id = product_id)


def search_post_request(request):
    search_query = request.POST["search_query"]
    return redirect(reverse('core:search_with_query', kwargs={"search_query": search_query}))


def add_to_shopping_cart(request, product_id, quantity=1):
    product = get_object_or_404(Product, pk=product_id)
    exists = OrderItem.objects.exists(product=product)
    if exists:
        order = OrderItem.objects.get(product=product)
        order.quantity += 1
        order.save()
        messages.success(request, "Item added to cart.")
        return redirect("core:product_details", pk=product_id)
    order_item = OrderItem.objects.create(product=product, quantity=quantity)
    cart, created = ShoppingCart.objects.get_or_create(user=request.user)
    cart.items.add(order_item)
    cart.save()
    messages.success(request, "Item added to cart.")
    return redirect("core:product_details", pk=product_id)


def change_quantity(request, product_id, change):
    order = OrderItem.objects.get(product=product_id)
    if change == "decrease":
        order.quantity -= 1
        order.save()
        return redirect('core:checkout_cart')
    order.quantity += 1
    order.save()
    return redirect('core:checkout_cart')
    

def remove_from_shopping_cart(request, item_id):
    cart = ShoppingCart.objects.get(user=request.user)
    item = OrderItem.objects.get(pk=item_id)
    cart.items.remove(item)
    cart.save()
    item.delete()
    messages.success(request, "Item has been removed from your cart.")
    return redirect("core:index")


def checkout_complete(request):
    cart = ShoppingCart.objects.get(user=request.user.id)
    subtotal = cart.subtotal
    ordered_items = []
    for each in cart.items.all():
        ordered_items.append(each)
        each.delete()

    try:
        send_mail(subject=f"Order #{cart.id} Confirmed", message="",
                  recipient_list=[request.user.email],
        html_message=get_html_email(ordered_items, subtotal))
    except Exception as e:
        print(e)

    cart.delete()
    return render(request, 'appcore/checkout_complete.html', {'ordered_items': ordered_items, 'subtotal': subtotal})

@csrf_exempt
def stripe_config(request):
    if request.method == "GET":
        stripe_config = {'public_key': settings.STRIPE_PUBLIC_KEY}
        return JsonResponse(stripe_config, safe=False)
        

@csrf_exempt
def create_checkout_session(request):
    cart, created = ShoppingCart.objects.get_or_create(user=request.user)
    items = []
    for item in cart.items.all():
        items.append({"price": item.product.price_id, "quantity": item.quantity})
    if request.method == 'GET':
        domain_url = 'http://localhost:8000/'
        stripe.api_key = settings.STRIPE_SECRET_KEY
        try:
            checkout_session = stripe.checkout.Session.create(
                success_url=domain_url + 'checkout_payment',
                cancel_url=domain_url + 'checkout_cart?payment=cancelled',
                payment_method_types=['card'],
                mode='payment',
                line_items=items
            )

appcore/templates/appcore/checkout_cart.html
{% extends 'appcore/base_boilerplate.html' %}
{% load static %}
{% block title %} Checkout Items - ColorAdmin {% endblock %}

{% block content %}
    <!-- BEGIN #checkout-cart -->
    <div class="section-container" id="checkout-cart">
        <!-- BEGIN container -->
        <div class="container">
            <!-- BEGIN checkout -->
            <div class="checkout">
                <form action="{% url 'core:checkout_cart' %}" method="POST" name="form_checkout">
                    {% csrf_token %}
                    <!-- BEGIN checkout-header -->
                    <div class="checkout-header">
                        <!-- BEGIN row -->
                        <div class="row">
                            <!-- BEGIN col-3 -->
                            <div class="col-md-3 col-sm-3">
                                <div class="step active">
                                    <a href="#">
                                        <div class="number">1</div>
                                        <div class="info">
                                            <div class="title">Delivery Options</div>
                                            <div class="desc">Review your items.</div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <!-- END col-3 -->
                            <!-- BEGIN col-3 -->
                            <div class="col-md-3 col-sm-3">
                                <div class="step">
                                    <a href="#">
                                        <div class="number">2</div>
                                        <div class="info">
                                            <div class="title">Shipping Address</div>
                                            <div class="desc">Add Shipping Details</div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <!-- END col-3 -->
                            <!-- BEGIN col-3 -->
                            <div class="col-md-3 col-sm-3">
                                <div class="step">
                                    <a href="#">
                                        <div class="number">3</div>
                                        <div class="info">
                                            <div class="title">Payment</div>
                                            <div class="desc">Add billing details.</div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <!-- END col-3 -->
                            <!-- BEGIN col-3 -->
                            <div class="col-md-3 col-sm-3">
                                <div class="step">
                                    <a href="#">
                                        <div class="number">4</div>
                                        <div class="info">
                                            <div class="title">Complete Payment</div>
                                            <div class="desc">Order Details</div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                            <!-- END col-3 -->
                        </div>
                        <!-- END row -->
                    </div>
                    <!-- END checkout-header -->
                    <!-- BEGIN checkout-body -->
                    <div class="checkout-body">
                        <div class="table-responsive">
                            <table class="table table-cart">
                                <thead>
                                    <tr>
                                        <th>Product Name</th>
                                        <th class="text-center">Price</th>
                                        <th class="text-center">Quantity</th>
                                        <th class="text-center">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for order in cart.items.all|dictsort:"product.product_name" %}
                                    <tr>
                                        <td class="cart-product">
                                            <div class="product-img">
                                                <img src="{{ order.product.product_image.url }}" alt="" />
                                            </div>
                                            <div class="product-info">
                                                <div class="title">{{order.product.product_name}}</div>
                                                <div class="desc">Delivers Tue 26/04/2016 - Free</div>
                                            </div>
                                        </td>
                                        <td class="cart-price text-center">${{order.product.discounted_price}}</td>
                                        <td class="cart-qty text-center">
                                            <div class="cart-qty-input">
                                                <a href="{% url 'core:change_quantity' order.product.id 'decrease' %}" class="qty-control left" ><i class="fa fa-minus"></i></a>
                                                <input type="text" name="qty" value="{{order.quantity}}" class="form-control" id="qty" />
                                                <a href="{% url 'core:change_quantity' order.product.id 'increase' %}" class="qty-control right" ><i class="fa fa-plus"></i></a>
                                            </div>
                                            <div class="qty-desc">1 to max order</div>
                                        </td>
                                        <td class="cart-total text-center">
                                            ${{order.total_cost}}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <td class="cart-summary" colspan="4">
                                            <div class="summary-container">
                                                <div class="summary-row">
                                                    <div class="field">Cart Subtotal</div>
                                                    <div class="value">${{cart.subtotal}}</div>
                                                </div>
                                                <div class="summary-row text-danger">
                                                    <div class="field">Free Shipping</div>
                                                    <div class="value">$0.00</div>
                                                </div>
                                                <div class="summary-row total">
                                                    <div class="field">Total</div>
                                                    <div class="value">${{cart.subtotal}}</div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- END checkout-body -->
                    <!-- BEGIN checkout-footer -->
                    <div class="checkout-footer">
                        <a href="#" class="btn btn-white btn-lg pull-left">Continue Shopping</a>
                        {% if cart.items.all|length > 0 %}
                        <button type="submit" class="btn btn-inverse btn-lg p-l-30 p-r-30 m-l-10">Checkout</button>
                        {% endif %}
                    </div>
                    <!-- END checkout-footer -->
                </form>
            </div>
            <!-- END checkout -->
        </div>
        <!-- END container -->
    </div>
    <!-- END #checkout-cart -->

    <!-- BEGIN #policy -->
    <div id="policy" class="section-container p-t-30 p-b-30 bg-white">
        <!-- BEGIN container -->
        <div class="container">
            <!-- BEGIN row -->
            <div class="row">
                <!-- BEGIN col-4 -->
                <div class="col-md-4 col-sm-4">
                    <!-- BEGIN policy -->
                    <div class="policy">
                        <div class="policy-icon"><i class="fa fa-truck"></i></div>
                        <div class="policy-info">
                            <h4>Free Delivery Over $100</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                    </div>
                    <!-- END policy -->
                </div>
                <!-- END col-4 -->
                <!-- BEGIN col-4 -->
                <div class="col-md-4 col-sm-4">
                    <!-- BEGIN policy -->
                    <div class="policy">
                        <div class="policy-icon"><i class="fa fa-shield"></i></div>
                        <div class="policy-info">
                            <h4>1 Year Warranty For Phones</h4>
                            <p>Cras laoreet urna id dui malesuada gravida. <br />Duis a lobortis dui.</p>
                        </div>
                    </div>
                    <!-- END policy -->
                </div>
                <!-- END col-4 -->
                <!-- BEGIN col-4 -->
                <div class="col-md-4 col-sm-4">
                    <!-- BEGIN policy -->
                    <div class="policy">
                        <div class="policy-icon"><i class="fa fa-user-md"></i></div>
                        <div class="policy-info">
                            <h4>6 Month Warranty For Accessories</h4>
                            <p>Fusce ut euismod orci. Morbi auctor, sapien non eleifend iaculis.</p>
                        </div>
                    </div>
                    <!-- END policy -->
                </div>
                <!-- END col-4 -->
            </div>
            <!-- END row -->
        </div>
        <!-- END container -->
    </div>
    <!-- END #policy -->
{% endblock %}